version: "3"

includes:
  mdox: ./Taskfile.mdox.yml

vars:
  COVERAGE_MIN: "70"
  goversion:
    sh: go env GOVERSION
  toolchain: '{{.goversion}}+auto'

tasks:
  default:
    desc: Start the blog service
    env:
      PLATFORM_DB_BLOG: "sqlite://blog.db"
    cmds:
      - go run ./cmd/blog

  playground:
    desc: Run the vuego template playground
    cmd: go run github.com/titpetric/vuego/cmd/vuego-playground theme

  generate:
    desc: Generate blog snapshot
    env:
      PLATFORM_DB_BLOG: "sqlite://blog.db"
    cmds:
      - task: fmt
      - go run ./cmd/generate

  fmt:
    desc: Format code and organize imports
    cmds:
      - goimports -w -local $(go list .) .
      - goimports-reviser -set-alias -format -imports-order "std,blanked,general,company,project" ./...
      - gofumpt -w .
      - go mod tidy

  fmt:check:
    desc: Check if code is formatted
    cmds:
      - test -z "$(goimports -l -local $(go list .) .)" || (echo "Code not formatted"; exit 1)
      - test -z "$(gofumpt -l .)" || (echo "Code not gofumpt'd"; exit 1)

  fmt:docs:
    desc: Format documentation
    cmds:
      - task: mdox:fmt

  lint:
    desc: Run golangci-lint
    cmds:
      - task: fmt
      - golangci-lint run ./...

  build:
    desc: Build the module
    cmds:
      - go build ./...

  test:
    desc: Run all tests with coverage
    deps:
      - fmt
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
    cmds:
      - go test -failfast -count=1 -cover -coverpkg=./... -coverprofile=pkg.cov ./...

  test:unit:
    desc: Run unit tests only
    cmds:
      - go test -v -short ./...

  test:integration:
    desc: Run integration tests only
    cmds:
      - go test -v -run Integration ./storage

  cover:
    desc: Generate coverage report and API documentation
    cmds:
      - go-fsck extract . --include-sources
      - go-fsck docs > docs/api.md
      - go tool cover -func=pkg.cov | summary coverfunc --json > pkg.cov.json
      - go-fsck extract --pretty-json ./...
      - go-fsck coverage -c pkg.cov.json -o go-fsck.json
      - go-fsck coverage --template=docs/testing-coverage.md.tpl -v > docs/testing-coverage.md
      - perl -pi -e 's/github.com\/titpetric/titpetric/g' docs/testing-coverage.md
      - task: fmt:docs

  uncover:
    desc: Show uncovered source
    cmd: uncover pkg.cov

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Tidy dependencies
    cmds:
      - go mod tidy

  deps:
    desc: Check for dependency updates
    cmds:
      - go list -u -m all

  clean:
    desc: Clean build artifacts and test files
    cmds:
      - rm -f pkg.cov pkg.cov.json go-fsck.json
      - rm -f docs/testing-coverage.md docs/api.md
      - go clean ./...

  bench:
    desc: Run benchmarks
    deps:
      - fmt
    cmds:
      - go test -bench=. -benchmem ./...

  bench:cpu:
    desc: Run benchmarks with CPU profiling
    cmds:
      - go test -bench=. -benchmem -cpuprofile=cpu.prof ./...
      - go tool pprof -http=:8080 cpu.prof

  bench:memory:
    desc: Run benchmarks with memory profiling
    cmds:
      - go test -bench=. -benchmem -memprofile=mem.prof ./...
      - go tool pprof -http=:8080 mem.prof

  ci:
    desc: Run CI checks (fmt, lint, vet, test, coverage)
    cmds:
      - task: fmt:check
      - task: lint
      - task: vet
      - task: test
      - task: cover

  all:
    desc: Format, lint, vet, test, build, and coverage
    cmds:
      - task: fmt
      - task: lint
      - task: vet
      - task: test
      - task: build
      - task: cover
