// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: proto/v1/client.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Client struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,10,opt,name=active,proto3" json:"active,omitempty"`
	Deleted       bool                   `protobuf:"varint,11,opt,name=deleted,proto3" json:"deleted,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_proto_v1_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_proto_v1_client_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Client) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Client) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Client) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Client) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_proto_v1_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_client_proto_rawDescGZIP(), []int{1}
}

func (x *CreateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Client                `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_proto_v1_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_client_proto_rawDescGZIP(), []int{2}
}

func (x *CreateClientResponse) GetResponse() *Client {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientRequest) Reset() {
	*x = UpdateClientRequest{}
	mi := &file_proto_v1_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientRequest) ProtoMessage() {}

func (x *UpdateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_client_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateClientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateClientRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *UpdateClientRequest) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type UpdateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Client                `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientResponse) Reset() {
	*x = UpdateClientResponse{}
	mi := &file_proto_v1_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientResponse) ProtoMessage() {}

func (x *UpdateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_client_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateClientResponse) GetResponse() *Client {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_proto_v1_client_proto protoreflect.FileDescriptor

const file_proto_v1_client_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/client.proto\x12\vplatform.v1\"}\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\n" +
	" \x01(\bR\x06active\x12\x18\n" +
	"\adeleted\x18\v \x01(\bR\adeleted\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\")\n" +
	"\x13CreateClientRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"G\n" +
	"\x14CreateClientResponse\x12/\n" +
	"\bresponse\x18\x01 \x01(\v2\x13.platform.v1.ClientR\bresponse\"k\n" +
	"\x13UpdateClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\"G\n" +
	"\x14UpdateClientResponse\x12/\n" +
	"\bresponse\x18\x01 \x01(\v2\x13.platform.v1.ClientR\bresponse2\xad\x01\n" +
	"\rClientService\x12M\n" +
	"\x06Create\x12 .platform.v1.CreateClientRequest\x1a!.platform.v1.CreateClientResponse\x12M\n" +
	"\x06Update\x12 .platform.v1.UpdateClientRequest\x1a!.platform.v1.UpdateClientResponseB(Z&github.com/titpetric/platform/proto/v1b\x06proto3"

var (
	file_proto_v1_client_proto_rawDescOnce sync.Once
	file_proto_v1_client_proto_rawDescData []byte
)

func file_proto_v1_client_proto_rawDescGZIP() []byte {
	file_proto_v1_client_proto_rawDescOnce.Do(func() {
		file_proto_v1_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_client_proto_rawDesc), len(file_proto_v1_client_proto_rawDesc)))
	})
	return file_proto_v1_client_proto_rawDescData
}

var file_proto_v1_client_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_v1_client_proto_goTypes = []any{
	(*Client)(nil),               // 0: platform.v1.Client
	(*CreateClientRequest)(nil),  // 1: platform.v1.CreateClientRequest
	(*CreateClientResponse)(nil), // 2: platform.v1.CreateClientResponse
	(*UpdateClientRequest)(nil),  // 3: platform.v1.UpdateClientRequest
	(*UpdateClientResponse)(nil), // 4: platform.v1.UpdateClientResponse
}
var file_proto_v1_client_proto_depIdxs = []int32{
	0, // 0: platform.v1.CreateClientResponse.response:type_name -> platform.v1.Client
	0, // 1: platform.v1.UpdateClientResponse.response:type_name -> platform.v1.Client
	1, // 2: platform.v1.ClientService.Create:input_type -> platform.v1.CreateClientRequest
	3, // 3: platform.v1.ClientService.Update:input_type -> platform.v1.UpdateClientRequest
	2, // 4: platform.v1.ClientService.Create:output_type -> platform.v1.CreateClientResponse
	4, // 5: platform.v1.ClientService.Update:output_type -> platform.v1.UpdateClientResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_client_proto_init() }
func file_proto_v1_client_proto_init() {
	if File_proto_v1_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_client_proto_rawDesc), len(file_proto_v1_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_client_proto_goTypes,
		DependencyIndexes: file_proto_v1_client_proto_depIdxs,
		MessageInfos:      file_proto_v1_client_proto_msgTypes,
	}.Build()
	File_proto_v1_client_proto = out.File
	file_proto_v1_client_proto_goTypes = nil
	file_proto_v1_client_proto_depIdxs = nil
}
