// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: proto/v1/session.proto

package v1

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ========================
// SessionService Interface
// ========================

type SessionService interface {
	// Get returns an User based on Session ID.
	Get(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
}

// ==============================
// SessionService Protobuf Client
// ==============================

type sessionServiceProtobufClient struct {
	client      HTTPClient
	urls        [1]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewSessionServiceProtobufClient creates a Protobuf client that implements the SessionService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewSessionServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) SessionService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "platform.v1", "SessionService")
	urls := [1]string{
		serviceURL + "Get",
	}

	return &sessionServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *sessionServiceProtobufClient) Get(ctx context.Context, in *GetSessionRequest) (*GetSessionResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "platform.v1")
	ctx = ctxsetters.WithServiceName(ctx, "SessionService")
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	caller := c.callGet
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetSessionRequest) (*GetSessionResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSessionRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSessionRequest) when calling interceptor")
					}
					return c.callGet(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSessionResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSessionResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sessionServiceProtobufClient) callGet(ctx context.Context, in *GetSessionRequest) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==========================
// SessionService JSON Client
// ==========================

type sessionServiceJSONClient struct {
	client      HTTPClient
	urls        [1]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewSessionServiceJSONClient creates a JSON client that implements the SessionService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewSessionServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) SessionService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "platform.v1", "SessionService")
	urls := [1]string{
		serviceURL + "Get",
	}

	return &sessionServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *sessionServiceJSONClient) Get(ctx context.Context, in *GetSessionRequest) (*GetSessionResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "platform.v1")
	ctx = ctxsetters.WithServiceName(ctx, "SessionService")
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	caller := c.callGet
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetSessionRequest) (*GetSessionResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSessionRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSessionRequest) when calling interceptor")
					}
					return c.callGet(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSessionResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSessionResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *sessionServiceJSONClient) callGet(ctx context.Context, in *GetSessionRequest) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =============================
// SessionService Server Handler
// =============================

type sessionServiceServer struct {
	SessionService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewSessionServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewSessionServiceServer(svc SessionService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &sessionServiceServer{
		SessionService:   svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *sessionServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *sessionServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// SessionServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const SessionServicePathPrefix = "/twirp/platform.v1.SessionService/"

func (s *sessionServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "platform.v1")
	ctx = ctxsetters.WithServiceName(ctx, "SessionService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "platform.v1.SessionService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "Get":
		s.serveGet(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *sessionServiceServer) serveGet(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *sessionServiceServer) serveGetJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetSessionRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.SessionService.Get
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetSessionRequest) (*GetSessionResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSessionRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSessionRequest) when calling interceptor")
					}
					return s.SessionService.Get(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSessionResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSessionResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetSessionResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetSessionResponse and nil error while calling Get. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sessionServiceServer) serveGetProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Get")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetSessionRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.SessionService.Get
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetSessionRequest) (*GetSessionResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSessionRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSessionRequest) when calling interceptor")
					}
					return s.SessionService.Get(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSessionResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSessionResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetSessionResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetSessionResponse and nil error while calling Get. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *sessionServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor2, 0
}

func (s *sessionServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *sessionServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "platform.v1", "SessionService")
}

var twirpFileDescriptor2 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0x80, 0x40,
	0x10, 0xc5, 0x91, 0x20, 0x72, 0x84, 0xc0, 0x0d, 0x22, 0x84, 0xfe, 0xe0, 0x21, 0xbc, 0xb4, 0x8b,
	0xf6, 0x0d, 0x0a, 0x92, 0xae, 0x4a, 0x10, 0x5d, 0x22, 0x75, 0xaa, 0x85, 0x74, 0xb7, 0x9d, 0xd1,
	0xcf, 0x1f, 0xe8, 0x2a, 0x46, 0x74, 0x7b, 0xbc, 0x79, 0xbf, 0x37, 0xc3, 0xc0, 0xa9, 0x75, 0x86,
	0x8d, 0x9a, 0x72, 0x45, 0x48, 0xa4, 0xcd, 0x20, 0x67, 0x43, 0x44, 0xf6, 0xeb, 0x8d, 0xdf, 0x8d,
	0xeb, 0xe5, 0x94, 0x27, 0x27, 0x5b, 0x68, 0x24, 0x74, 0x4b, 0x22, 0x2d, 0x20, 0x2e, 0x91, 0xeb,
	0x85, 0xaa, 0xf0, 0x7b, 0x44, 0x62, 0x71, 0x0e, 0xe0, 0x7b, 0x5e, 0x75, 0x77, 0x16, 0x5c, 0x05,
	0x59, 0x58, 0x85, 0xde, 0x79, 0xec, 0xd2, 0x7b, 0x10, 0x7b, 0x86, 0xac, 0x19, 0x08, 0xc5, 0x0d,
	0x1c, 0x39, 0xaf, 0x67, 0x24, 0x2a, 0x62, 0xb9, 0x5b, 0x2f, 0x9f, 0x08, 0x5d, 0xb5, 0x45, 0x8a,
	0x67, 0x38, 0xf6, 0x0d, 0x35, 0xba, 0x49, 0xb7, 0x28, 0x1e, 0xe0, 0xa0, 0x44, 0x16, 0x17, 0xbf,
	0xa8, 0x3f, 0xc7, 0x25, 0x97, 0xff, 0xce, 0x97, 0xe6, 0xbb, 0xec, 0xe5, 0xfa, 0x43, 0xf3, 0xe7,
	0xd8, 0xc8, 0xd6, 0xf4, 0x8a, 0x35, 0x5b, 0x64, 0xa7, 0x5b, 0xb5, 0x62, 0x6a, 0xfd, 0x43, 0x73,
	0x38, 0xab, 0xdb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x69, 0x1a, 0xeb, 0xbd, 0x3f, 0x01, 0x00,
	0x00,
}
