// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/v1/client.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/titpetric/platform/proto/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ClientServiceName is the fully-qualified name of the ClientService service.
	ClientServiceName = "platform.v1.ClientService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ClientServiceCreateProcedure is the fully-qualified name of the ClientService's Create RPC.
	ClientServiceCreateProcedure = "/platform.v1.ClientService/Create"
	// ClientServiceUpdateProcedure is the fully-qualified name of the ClientService's Update RPC.
	ClientServiceUpdateProcedure = "/platform.v1.ClientService/Update"
)

// ClientServiceClient is a client for the platform.v1.ClientService service.
type ClientServiceClient interface {
	Create(context.Context, *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error)
	Update(context.Context, *connect.Request[v1.UpdateClientRequest]) (*connect.Response[v1.UpdateClientResponse], error)
}

// NewClientServiceClient constructs a client for the platform.v1.ClientService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewClientServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ClientServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	clientServiceMethods := v1.File_proto_v1_client_proto.Services().ByName("ClientService").Methods()
	return &clientServiceClient{
		create: connect.NewClient[v1.CreateClientRequest, v1.CreateClientResponse](
			httpClient,
			baseURL+ClientServiceCreateProcedure,
			connect.WithSchema(clientServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.UpdateClientRequest, v1.UpdateClientResponse](
			httpClient,
			baseURL+ClientServiceUpdateProcedure,
			connect.WithSchema(clientServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
	}
}

// clientServiceClient implements ClientServiceClient.
type clientServiceClient struct {
	create *connect.Client[v1.CreateClientRequest, v1.CreateClientResponse]
	update *connect.Client[v1.UpdateClientRequest, v1.UpdateClientResponse]
}

// Create calls platform.v1.ClientService.Create.
func (c *clientServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls platform.v1.ClientService.Update.
func (c *clientServiceClient) Update(ctx context.Context, req *connect.Request[v1.UpdateClientRequest]) (*connect.Response[v1.UpdateClientResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// ClientServiceHandler is an implementation of the platform.v1.ClientService service.
type ClientServiceHandler interface {
	Create(context.Context, *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error)
	Update(context.Context, *connect.Request[v1.UpdateClientRequest]) (*connect.Response[v1.UpdateClientResponse], error)
}

// NewClientServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewClientServiceHandler(svc ClientServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	clientServiceMethods := v1.File_proto_v1_client_proto.Services().ByName("ClientService").Methods()
	clientServiceCreateHandler := connect.NewUnaryHandler(
		ClientServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(clientServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	clientServiceUpdateHandler := connect.NewUnaryHandler(
		ClientServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(clientServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.v1.ClientService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ClientServiceCreateProcedure:
			clientServiceCreateHandler.ServeHTTP(w, r)
		case ClientServiceUpdateProcedure:
			clientServiceUpdateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedClientServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedClientServiceHandler struct{}

func (UnimplementedClientServiceHandler) Create(context.Context, *connect.Request[v1.CreateClientRequest]) (*connect.Response[v1.CreateClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.ClientService.Create is not implemented"))
}

func (UnimplementedClientServiceHandler) Update(context.Context, *connect.Request[v1.UpdateClientRequest]) (*connect.Response[v1.UpdateClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.ClientService.Update is not implemented"))
}
