// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/v1/user.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/titpetric/platform/proto/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "platform.v1.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceCreateProcedure is the fully-qualified name of the UserService's Create RPC.
	UserServiceCreateProcedure = "/platform.v1.UserService/Create"
	// UserServiceUpdateProcedure is the fully-qualified name of the UserService's Update RPC.
	UserServiceUpdateProcedure = "/platform.v1.UserService/Update"
)

// UserServiceClient is a client for the platform.v1.UserService service.
type UserServiceClient interface {
	Create(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	Update(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
}

// NewUserServiceClient constructs a client for the platform.v1.UserService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := v1.File_proto_v1_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		create: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+UserServiceCreateProcedure,
			connect.WithSchema(userServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.UpdateUserRequest, v1.UpdateUserResponse](
			httpClient,
			baseURL+UserServiceUpdateProcedure,
			connect.WithSchema(userServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	create *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	update *connect.Client[v1.UpdateUserRequest, v1.UpdateUserResponse]
}

// Create calls platform.v1.UserService.Create.
func (c *userServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls platform.v1.UserService.Update.
func (c *userServiceClient) Update(ctx context.Context, req *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the platform.v1.UserService service.
type UserServiceHandler interface {
	Create(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	Update(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := v1.File_proto_v1_user_proto.Services().ByName("UserService").Methods()
	userServiceCreateHandler := connect.NewUnaryHandler(
		UserServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(userServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateHandler := connect.NewUnaryHandler(
		UserServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(userServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	return "/platform.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceCreateProcedure:
			userServiceCreateHandler.ServeHTTP(w, r)
		case UserServiceUpdateProcedure:
			userServiceUpdateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) Create(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.UserService.Create is not implemented"))
}

func (UnimplementedUserServiceHandler) Update(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("platform.v1.UserService.Update is not implemented"))
}
